src/PermissionServerDemo.Identity/Pages/Account/ChangeEmailConfirmation.cshtml.cs
using System;
using System.Text;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;

namespace PermissionServerDemo.Identity.Pages.Account
{
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    [SecurityHeaders]
    public class ChangeEmailConfirmationModel : PageModel
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public ChangeEmailConfirmationModel(UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
        }

        [ViewData]
        public bool Success { get; set; }
        [ViewData]
        public string ResultMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string email, string code)
        {
            if (userId == null || email == null || code == null)
                return RedirectToPage("error");

            // Retrieve associated User and change their email
            var user = await _userManager.FindByIdAsync(userId);
            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            // Note: ChangeEmailAsync also sets EmailConfirmed to true
            var result = await _userManager.ChangeEmailAsync(user, email, code);
            Success = result.Succeeded;
            if (result.Succeeded)
            {
                // Currently, username is the same as email so we need to change both before success
                var setUserNameResult = await _userManager.SetUserNameAsync(user, email);
                if (setUserNameResult.Succeeded)
                {
                    await _signInManager.RefreshSignInAsync(user);
                    ResultMessage = "Your email has successfully been changed.";
                    return Page();
                }
            }
            ResultMessage = "The link you clicked was either expired or invalid. Please have a valid email change link sent to your email.";
            return Page();
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/ConfirmEmail.cshtml.cs
using System;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PermissionServerDemo.Identity.Pages.Account
{
    [AllowAnonymous]
    [SecurityHeaders]
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        public ConfirmEmailModel(UserManager<User> userManager)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        [ViewData]
        public bool Success { get; set; }

        [ViewData]
        public string ResultMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (String.IsNullOrEmpty(userId) || String.IsNullOrEmpty(code))
                return RedirectToPage("/error/notfound");
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var result = await _userManager.ConfirmEmailAsync(user, code);
                if (result.Succeeded)
                {
                    Success = true;
                    ResultMessage = "Your email has successfully been confirmed. Thank you.";
                    return Page();
                }
            }
            Success = false;
            ResultMessage = "The link provided was invalid or has expired. Please have a valid link sent to your email.";
            return Page();
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/ForgotPassword.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PermissionServerDemo.Identity.Pages.Account
{
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    [SecurityHeaders]
    public class ForgotPasswordModel : PageModel
    {
        private readonly IAccountEmailService _acctEmailService;

        public ForgotPasswordModel(IAccountEmailService acctEmailService)
        {
            _acctEmailService = acctEmailService ?? throw new ArgumentNullException(nameof(acctEmailService));
        }

        [ViewData]
        public string SuccessMessage { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email Address")]
            public string Email { get; set; }
        }
        public IActionResult OnGetAsync()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                await _acctEmailService.SendPassResetEmail(Input.Email);
                SuccessMessage = "If a verified account exists with this email, a password reset link has been sent to it.";
            }
            return Page();
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/Login.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Extensions;
using PermissionServerDemo.Identity.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Events;
using Duende.IdentityServer.Models;

namespace PermissionServerDemo.Identity.Pages.Account
{
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    [SecurityHeaders]
    public class LoginModel : PageModel
    {
        private readonly ILogger<LoginModel> _logger;
        private readonly IIdentityServerInteractionService _interactionSvc;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private IEventService _eventSvc;
        public LoginModel(ILogger<LoginModel> logger,
            IConfiguration config,
            IIdentityServerInteractionService interactionSvc,
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEventService eventService)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _interactionSvc = interactionSvc ?? throw new ArgumentNullException(nameof(interactionSvc));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
            _eventSvc = eventService ?? throw new ArgumentNullException(nameof(eventService));
        }
        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            public string Email { get; set; }
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task<IActionResult> OnGetAsync(string returnUrl = null)
        {
            var context = await _interactionSvc.GetAuthorizationContextAsync(returnUrl);
            // Redirect as necessary if user is already logged in
            if (User?.Identity.IsAuthenticated == true)
                return RedirectUponLogin(context, returnUrl);

            if (context?.IdP != null)
            {
                _logger.LogWarning("External login service requested, but not implemented.");
                return RedirectToPage("error");
            }

            var model = new InputModel()
            {
                Email = context?.LoginHint,
            };
            ReturnUrl = returnUrl;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            // Get context of request
            var context = await _interactionSvc.GetAuthorizationContextAsync(ReturnUrl);

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: true);
                if (result.Succeeded)
                {

                    var user = await _userManager.FindByEmailAsync(Input.Email);
                    await _eventSvc.RaiseAsync(new UserLoginSuccessEvent(user.UserName, user.Id.ToString(), user.UserName, clientId: context?.Client.ClientId));
                    // Login successful and logged, now redirect user
                    return RedirectUponLogin(context, ReturnUrl);
                }
                else if (result.IsNotAllowed)
                {
                    ModelState.AddModelError(String.Empty, $"Your account must be confirmed before logging in. Need a new confirmation link? <a href='/account/resendconfirmationemail'>Click here</a>");
                    return Page();
                }
                else if (result.IsLockedOut)
                {
                    ModelState.AddModelError(String.Empty, $"Your account is locked out. Please wait 10 minutes before attempting to sign in again.");
                    return Page();
                }
                ModelState.AddModelError(String.Empty, "Invalid email or password.");
            }
            // Return view with errors
            return Page();
        }
        /// <summary>
        /// Redirects the logged in user back to its native client, redirectUrl, or the Idp home page.
        /// </summary>
        private IActionResult RedirectUponLogin(AuthorizationRequest context, string returnUrl)
        {
            if (context != null)
            {
                return Redirect(returnUrl);
            }
            // Else if local, redirect
            else if (Url.IsLocalUrl(returnUrl))
            {
                return LocalRedirect(returnUrl);
            }
            // Return to home if ReturnUrl is null or invalid
            else
            {
                return RedirectToPage("/home/index");
            }
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/ResendConfirmationEmail.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PermissionServerDemo.Identity.Pages.Account
{
    [AllowAnonymous]
    [ValidateAntiForgeryToken]
    [SecurityHeaders]
    public class ResendConfirmationEmailModel : PageModel
    {
        private readonly IAccountEmailService _acctEmailService;

        public ResendConfirmationEmailModel(IAccountEmailService acctEmailService)
        {
            _acctEmailService = acctEmailService ?? throw new ArgumentNullException(nameof(acctEmailService));
        }

        [ViewData]
        public string SuccessMessage { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email Address")]
            public string Email { get; set; }
        }

        public IActionResult OnGetAsync()
        {
            return Page();
        }

        /// <summary>
        /// Attempts to send email confirmation, updates page with results.
        /// </summary>
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var result = await _acctEmailService.SendConfToUnauthUserAsync(Input.Email);
                // Update viewdata, redisplay form
                result.Match(
                    e => ModelState.AddModelError("", e),
                    () => SuccessMessage = $"A confirmation link has been sent to {Input.Email} if applicable. You may need to check your spam folder."
                );
            }
            return Page();
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/Settings/Email.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using PermissionServerDemo.Identity.Extensions;
using PermissionServerDemo.Identity.Interfaces;
using PermissionServerDemo.Identity.Entities;
using IdentityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PermissionServerDemo.Identity.Pages.Account.Settings
{
    [Authorize]
    [ValidateAntiForgeryToken]
    [SecurityHeaders]
    public class EmailModel : PageModel
    {
        private readonly ILogger<PageModel> _logger;
        private readonly UserManager<User> _userManager;
        private readonly IAccountEmailService _acctEmailService;

        public EmailModel(ILogger<PageModel> logger,
            UserManager<User> userManager,
            IAccountEmailService acctEmailService)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _acctEmailService = acctEmailService ?? throw new ArgumentNullException(nameof(acctEmailService));
        }

        [ViewData]
        public string SuccessMessage { get; set; }

        [ViewData]
        [EmailAddress]
        [Display(Name = "Current Email")]
        public string CurrentEmail { get; set; }

        [ViewData]
        public bool EmailConfirmed { get; set; }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [EmailAddress]
            [Display(Name = "New Email")]
            public string NewEmail { get; set; }
        }
        public async Task<IActionResult> OnGetAsync()
        {
            var userId = User.FindFirst(JwtClaimTypes.Subject)?.Value;
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                SetPrepopulatedFormData(user);
                return Page();
            }
            _logger.LogEmptyAuthenticatedUser(user);
            return RedirectToPage("error");
        }

        public async Task<IActionResult> OnPostChangeEmailAsync()
        {
            var userId = User.FindFirst(JwtClaimTypes.Subject)?.Value;
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // Manually check email field so multiple forms can be present on page
                if (!String.IsNullOrEmpty(Input.NewEmail))
                {
                    var res = await _acctEmailService.SendEmailChangeEmail(user.Email, Input.NewEmail);
                    res.Match(
                        e => ModelState.AddModelError("", e),
                        () => SuccessMessage = $"An email containing a link to confirm your email change has been sent to {Input.NewEmail}."
                    );
                    SetPrepopulatedFormData(user);
                    return Page();
                }
                ModelState.AddModelError("", "The NewEmail field is required.");
                SetPrepopulatedFormData(user);
                return Page();
            }
            _logger.LogEmptyAuthenticatedUser(user);
            return RedirectToPage("error");
        }

        public async Task<IActionResult> OnPostSendConfAsync()
        {
            var userId = User.FindFirst(JwtClaimTypes.Subject)?.Value;
            var user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var res = await _acctEmailService.SendConfToAuthUserAsync(user);
                res.Match(
                    e => ModelState.AddModelError("", e),
                    () => SuccessMessage = $"A confirmation link has been sent to {Input.NewEmail}. You may need to check your spam folder."
                );
                SetPrepopulatedFormData(user);
                return Page();
            }
            _logger.LogEmptyAuthenticatedUser(user);
            return RedirectToPage("error");
        }

        [NonHandler]
        private void SetPrepopulatedFormData(User user)
        {
            CurrentEmail = user.Email;
            EmailConfirmed = user.EmailConfirmed;
        }
    }
}

src/PermissionServerDemo.Identity/Pages/Account/Settings/Email.cshtml
@page
@model EmailModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Account - Email";
}
<div class="row tabs">
    <a href="@Url.Page("/account/settings/profile")" class="tab col-3 col-sm-2">
        Profile
    </a>
    <a href="@Url.Page("/account/settings/email")" class="tab col-3 col-sm-2"  data-selected="true">
        Email
    </a>
    <a href="@Url.Page("/account/settings/password")" class="tab col-3 col-sm-2">
        Password
    </a>
</div>
<div class="row m-0 panel-content shadow-sm">
    <div class="panel-acct-settings panel-fill">
        <div class="panel-acct-contents">
            <div class="acct-form">
                <h3>Email Details</h3>
                <hr />
                <div class="row m-0">
                    <div class="col-sm-12">
                        @* Success summary *@
                        @await Html.PartialAsync("_SuccessSummaryPartial", ViewData)
                        @* Custom validation-summary *@
                        @await Html.PartialAsync("_ValidationSummaryPartial", ModelState)
                        <div class="form-group row">
                            <label asp-for="CurrentEmail" class="col-sm-3 col-form-label"></label>
                            <div class="col-sm-9">
                                <div class="form-control-plaintext">@Model.CurrentEmail</div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Status</label>
                            <div class="col-sm-9">
                                @if (Model.EmailConfirmed) {
                                    <div class="form-control-plaintext"><i class="fas fa-check fa-lg text-success"></i> Confirmed</div>
                                } else {
                                    <form method="post" asp-page-handler="sendconf">
                                        <div class="form-control-plaintext">Not Confirmed - <button type="submit" class="btn btn-link">Resend confirmation</button></div>
                                    </form>
                                }
                            </div>
                        </div>
                        <form method="post" asp-page-handler="changeemail">
                            <div class="form-group row">
                                <label asp-for="Input.NewEmail" class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Input.NewEmail" class="form-control" />
                                    <span asp-validation-for="Input.NewEmail" class="text-danger"></span>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Update Email</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/PermissionServerDemo.Identity/Pages/Account/Settings/Password.cshtml
@page
@model PasswordModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Account - Password";
}
<div class="row tabs">
    <a href="@Url.Page("/account/settings/profile")" class="tab col-3 col-sm-2">
        Profile
    </a>
    <a href="@Url.Page("/account/settings/email")" class="tab col-3 col-sm-2">
        Email
    </a>
    <a href="@Url.Page("/account/settings/password")" class="tab col-3 col-sm-2" data-selected="true">
        Password
    </a>
</div>
<div class="row m-0 panel-content shadow-sm">
    <div class="panel-acct-settings panel-fill">
        <div class="panel-acct-contents">
            <div class="acct-form">
                <h3>Password Details</h3>
                <hr />
                <div class="row m-0">
                    <div class="col-sm-12">
                        <form method="post">
                            @* Success summary *@
                            @await Html.PartialAsync("_SuccessSummaryPartial", ViewData)
                            <div class="form-group row">
                                <label asp-for="Input.CurrentPassword" class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Input.CurrentPassword" class="form-control" />
                                    <span asp-validation-for="Input.CurrentPassword" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Input.NewPassword" class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Input.NewPassword" class="form-control" />
                                    <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Input.ConfirmNewPassword" class="col-sm-3 col-form-label"></label>
                                <div class="col-sm-9">
                                    <input asp-for="Input.ConfirmNewPassword" class="form-control" />
                                    <span asp-validation-for="Input.ConfirmNewPassword" class="text-danger"></span>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/PermissionServerDemo.Identity/Pages/Account/Settings/Profile.cshtml
@page
@model ProfileModel
@{
    Layout = "~/Pages/Shared/_Layout.cshtml";
    ViewData["Title"] = "Account - Profile";
}
<div class="row tabs">
    <a href="@Url.Page("/account/settings/profile")" class="tab col-3 col-sm-2" data-selected="true">
        Profile
    </a>
    <a href="@Url.Page("/account/settings/email")" class="tab col-3 col-sm-2">
        Email
    </a>
    <a href="@Url.Page("/account/settings/password")" class="tab col-3 col-sm-2">
        Password
    </a>
</div>
<div class="row m-0 panel-content shadow-sm">
    <div class="panel-acct-settings panel-fill">
        <div class="panel-acct-contents">
            <div class="acct-form">
                <h3>Profile Details</h3>
                <hr />
                <div class="row m-0">
                    <div class="col-sm-12">
                        <form method="post">
                            @* Success summary *@
                            @await Html.PartialAsync("_SuccessSummaryPartial", ViewData)
                            <div class="form-group row">
                                <label asp-for="Input.FirstName" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Input.FirstName" class="form-control" value="@Model.CurrentFirstName" />
                                    <span asp-validation-for="Input.FirstName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label asp-for="Input.LastName" class="col-sm-2 col-form-label"></label>
                                <div class="col-sm-10">
                                    <input asp-for="Input.LastName" class="form-control" value="@Model.CurrentLastName" />
                                    <span asp-validation-for="Input.LastName" class="text-danger"></span>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Update Profile</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>